# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Infinite Draft & Co.
email: yichenliu17@gmail.com
description: Bug Driven Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://infinite-draft.github.io" # the base hostname & protocol for your site
github_username: infinite-draft
paginate: 4
theme-dark: true #Set to true to change to dark website theme
plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
